# Site settings
title: Raymond Ginnings II
name: Raymond Ginnings II

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/RGinnings
 - title: StackOverflow
   url: https://stackoverflow.com/users/10207496/raymond-ginnings
 - title: LinkedIn
   url: www.linkedin.com/in/raymond-ginnings

#Any buzzword skills you want to include
skills:
 - Java
 - Javascript
 - SQL
 - Ladder Logic
 - Microsoft Word
 - Microsoft Excel
 - Mircosoft Powerpoint
 - Microsoft Outlook
 - Microsoft Visio
 - Windows 7, 10
 - Previously held Top Secret Security Clearance
 - Responsible
 - Detail Oriented
 - Can work with a team or individualy
 - Android Studio
 - Intellij
 - Netbeans
 
  
#Work experience is required
roles:
 - title: IT System Analyst
   start: 2019
   end: Ongoing
   employer: Magna Seating
   description: Overnight IT assembly line support
 - title: Assembly Line Worker
   start: 2015
   end: 2019
   employer: Magna Seating
   description: Worked as assembly line worker
 - title: Customs Protection Officer
   start: 2013
   end: 2015
   employer: G4S Security
   description: Overnight Armed security officer
 - title: Specialist US Army
   start: 2009
   end: 2013
   employer: US Army
   description: One deployment 2009-2010 Combat arms Cannon Crewmember
   
#Education is required
education:
 - level: Bachelor of Science
   date: 2019
   subject: Software Application Programming
   school: Colorado Technical University

#List of interesting Github repo/projects to include - optional
github:
 - RGinnings/workout
 - RGinnings/HiitTimer
 - RGinnings/caesarCipher

intro: |
  I live in Excelsior Springs, Missouri and I am currently working as the IT System Analyst, overnight at a seating manufacturing plant. I graduated college with my Bachelor's Degree and within 6 months I recieved my offer to become one of the IT at my currently place of employment. I worked my way from assembler while going to college and then to their IT Department. I have a lot of determination and willingness to learn. I like to create new things, mostly those that help others complete tasks faster and in a simpler fasion. 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: I have created a couple of things, currently posted to my GitHub, for friends/family to help out in daily workouts or just fun things to message each other with.  <br/>
